name: Deploy prod to Heroku
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: git clone
        uses: actions/checkout@v2
      - name: linter
        uses: michaelw90/PHP-lint@master
      - name: Security checker
        uses: symfonycorp/security-checker-action@v2
      - name: PHPstan
        uses: docker://oskarstark/phpstan-ga
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v3
        with:
          urls: |
            http://iim-a4-projet-laravel-prod.herokuapp.com/
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage>
      - name: Deploy heroku
        uses: akhileshns/heroku-deploy@v3.5.6 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_KEY_PROD}}
          heroku_app_name: ${{secrets.HEROKU_APP_PROD}} #Must be unique in Heroku
          heroku_email: ${{secrets.HEROKU_EMAIL_PROD}}
          branch: master
