name: Deploy prod to Heroku
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: git clone
        uses: actions/checkout@v2
      - name: install sqlite3
        run: sudo apt-get install php7.3-sqlite -y
      - name: stop
        run: sudo service apache2 stop
      - name: restart
        run: sudo service apache2 restart
      - name: Install Dependencies (PHP vendors)
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Create DB and schemas
        run: |
          mkdir -p database
          touch database/database.sqlite
          php artisan migrate
     # - name: linter
      #  uses: michaelw90/PHP-lint@master
      - name: Security checker
        uses: symfonycorp/security-checker-action@v2
      # - name: Laravel PHP Insights
      #  uses: stefanzweifel/laravel-phpinsights-action@v1.1.1
      - name: Deploy heroku
        uses: akhileshns/heroku-deploy@v3.5.6 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_KEY_PROD}}
          heroku_app_name: ${{secrets.HEROKU_APP_PROD}} #Must be unique in Heroku
          heroku_email: ${{secrets.HEROKU_EMAIL_PROD}}